IN: bert.constants

CONSTANT: SMALL_INT 97
CONSTANT: INT 98
CONSTANT: FLOAT 99
CONSTANT: ATOM 100
CONSTANT: SMALL_TUPLE 104
CONSTANT: LARGE_TUPLE 105
CONSTANT: NIL 106
CONSTANT: STRING 107
CONSTANT: LIST 108
CONSTANT: BIN 109
CONSTANT: SMALL_BIGNUM 110
CONSTANT: LARGE_BIGNUM 111
CONSTANT: VERSION 131

SYMBOLS: bert true false dict time regex ;
SYMBOLS: caseless dollar_endonly ;
SYMBOL: bert-vocab
